import type { TokenMatterData, TokenSegment } from "./types";

export const MOCK_TOKEN_SEGMENTS: TokenSegment[] = [
  {
    id: "seg-1",
    startToken: 0,
    endToken: 42500,
    mission: "Bootstrap AST parser architecture",
    agent: "CORTEX-ORCHESTRATOR",
    model: "Cortex-Core v2.4",
    category: "input",
    timestamp: "19:12:04",
  },
  {
    id: "seg-2",
    startToken: 42500,
    endToken: 68200,
    mission: "Bootstrap AST parser architecture",
    agent: "CORTEX-ORCHESTRATOR",
    model: "Cortex-Core v2.4",
    category: "reasoning",
    timestamp: "19:14:22",
  },
  {
    id: "seg-3",
    startToken: 68200,
    endToken: 89400,
    mission: "Synthesize token hierarchy diffs",
    agent: "CLAUDE-SONNET",
    model: "Claude 3.5 Sonnet",
    category: "output",
    timestamp: "19:35:10",
  },
  {
    id: "seg-4",
    startToken: 89400,
    endToken: 96595,
    mission: "Context cache warm-up & replay",
    agent: "CORTEX-CACHE",
    model: "Cortex KV Cache",
    category: "cache",
    timestamp: "20:01:45",
  },
  {
    id: "seg-5",
    startToken: 96595,
    endToken: 145000,
    mission: "Refactor multi-agent telemetry",
    agent: "AG-CODEX",
    model: "GPT-5.6",
    category: "input",
    timestamp: "21:18:30",
  },
  {
    id: "seg-6",
    startToken: 145000,
    endToken: 171200,
    mission: "Fix token telemetry & Hilbert space",
    agent: "AG-CODEX",
    model: "GPT-5.6",
    category: "reasoning",
    timestamp: "21:42:08",
  },
  {
    id: "seg-7",
    startToken: 171200,
    endToken: 184392,
    mission: "Validate precision matter geometry",
    agent: "KIMI-EXPLORER",
    model: "Kimi-v1.5",
    category: "output",
    timestamp: "21:58:34",
  },
];

export const DEFAULT_TOKEN_MATTER_MOCK: TokenMatterData = {
  total: 184392,
  today: 12841,
  capacity: 1048576,
  categories: {
    input: 121084,
    output: 31203,
    reasoning: 24910,
    cache: 7195,
  },
  segments: MOCK_TOKEN_SEGMENTS,
};
